== The Yocto Project

=== Obtaining an image generated by Yocto Project

The first step is to prepare the host machine and download the source code.

==== Update the host needed packages

.Ubuntu
[source,console]
$ sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat libsdl1.2-dev xterm

NOTE:: If you use a different distribution, see http://www.yoctoproject.org/docs/current/yocto-project-qs/yocto-project-qs.html

==== Dowload the metadata

[source,console]
$ mkdir ~/bin
$ curl http://commondatastorage.googleapis.com/git-repo-downloads/repo >  ~/bin/repo
$ chmod a+x ~/bin/repo
$ PATH=${PATH}:~/bin
$ mkdir fsl-community-bsp
$ cd fsl-community-bsp
$ repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b rocko
$ repo sync

You can also download a prebuilt image from http://freescale.github.io/#download and test it on your board.

The download can take some time (such as 15 minutes) and depends on your Internet connection (please, make sure your proxy does allow your to download from external sources).

After the download is completed, enable your environment:

==== Building

[source,console]
$ MACHINE=imx7s-warp DISTRO=fslc-framebuffer source setup-environment build

NOTE:: Please read the EULA and only press *y* if you accept it.

After the environment is setup you have the following files:

user@b19406-2:/code/yocto/master/build2$ tree

[source,console]
$ tree
.
└── conf
    ├── bblayers.conf
    ├── local.conf
    ├── local.conf.sample
    └── templateconf.cfg

After configuring the Yocto Project to use WaRP7 machine, you can build any desired image, such as:

[source,console]
$ bitbake fsl-image-machine-test

The first build can take several hours (depending on your machine). When it completes the result can be found on `tmp/deploy/image/imx7s-warp`.

=== Steps to update the image

.board steps (u-boot)
[source,console]
=> ums 0 mmc 0

.host steps
[source,console]
$ gunzip -f <image-name>.wic.gz
$ sudo dd if=<image-name>.wic of=/dev/sdX

It may take few minutes. As soon as the dd command is finished, you can reboot the board.

=== 
