== The Yocto Project

=== Obtaining an image generated by Yocto Project

The first step is to prepare the host machine and download the source code.

==== Update the host needed packages

.Ubuntu
[source,console]
$ sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat libsdl1.2-dev xterm

NOTE:: If you use a different distribution, see http://www.yoctoproject.org/docs/current/yocto-project-qs/yocto-project-qs.html

==== Dowload the metadata

[source,console]
$ mkdir ~/bin
$ curl http://commondatastorage.googleapis.com/git-repo-downloads/repo >  ~/bin/repo
$ chmod a+x ~/bin/repo
$ PATH=${PATH}:~/bin
$ mkdir fsl-community-bsp
$ cd fsl-community-bsp
$ repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b pyro
$ repo sync

You can also download a prebuilt image from http://freescale.github.io/#download and test it on your board.

The download can take some time (such as 15 minutes) and depends on your Internet connection (please, make sure your proxy does allow your to download from external sources).

After the download is completed, enable your environment:

==== Building

[source,console]
$ source setup-environment build

NOTE:: Please read the EULA and only press *y* if you accept it.

After the environment is setup you have the following files:

user@b19406-2:/code/yocto/master/build2$ tree

[source,console]
$ tree
.
└── conf
    ├── bblayers.conf
    ├── local.conf
    ├── local.conf.sample
    └── templateconf.cfg

Change file `conf/local.conf` to configure the build system to target the WaRP7 machine as the following example:

[source]
----
MACHINE ??= 'imx7s-warp'
DISTRO ?= 'poky'
PACKAGE_CLASSES ?= "package_rpm"
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats image-mklibs"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS = "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    ABORT,${TMPDIR},100M,1K \
    ABORT,${DL_DIR},100M,1K \
    ABORT,${SSTATE_DIR},100M,1K \
    ABORT,/tmp,10M,1K"
PACKAGECONFIG_append_pn-qemu-native = " sdl"
PACKAGECONFIG_append_pn-nativesdk-qemu = " sdl"
CONF_VERSION = "1"

DL_DIR ?= "${BSPDIR}/downloads/"
ACCEPT_FSL_EULA = "1"
----

NOTE:: The WaRP7 machine name is **imx7s-warp**

After configuring the Yocto Project to use WaRP7 machine, you can build any desired image, such as:

[source,console]
$ bitbake fsl-image-machine-test

The first build can take several hours (depending on your machine). When it completes the result can be found on `tmp/deploy/image/imx7s-warp` as show in the following example:

[source,console]
$ ls -l tmp/deploy/images/imx7s-warp/
total 263084
-rw-r--r-- 1 user user 67108864 Ago  8 11:58 core-image-base-imx7s-warp-20160808141615.rootfs.ext4
-rw-r--r-- 1 user user     9568 Ago  8 11:58 core-image-base-imx7s-warp-20160808141615.rootfs.manifest
-rw-r--r-- 1 user user 83886080 Ago  8 11:58 core-image-base-imx7s-warp-20160808141615.rootfs.sdcard
-rw-r--r-- 1 user user 67108864 Ago  8 12:55 core-image-base-imx7s-warp-20160808155513.rootfs.ext4
-rw-r--r-- 1 user user     9568 Ago  8 12:55 core-image-base-imx7s-warp-20160808155513.rootfs.manifest
-rw-r--r-- 1 user user 83886080 Ago  8 12:55 core-image-base-imx7s-warp-20160808155513.rootfs.sdcard
lrwxrwxrwx 1 user user       53 Ago  8 12:55 core-image-base-imx7s-warp.ext4 -> core-image-base-imx7s-warp-20160808155513.rootfs.ext4
lrwxrwxrwx 1 user user       57 Ago  8 12:55 core-image-base-imx7s-warp.manifest -> core-image-base-imx7s-warp-20160808155513.rootfs.manifest
lrwxrwxrwx 1 user user       58 Ago  8 12:55 core-image-base-imx7s-warp.sdcard.gz -> core-image-base-imx7s-warp-20160808155513.rootfs.sdcard.gz
-rw-rw-r-- 2 user user   804917 Ago  8 10:28 modules--4.1-1.0.x+git0+b8fb01d418-r0-imx7s-warp-20160808132254.tgz
lrwxrwxrwx 1 user user       67 Ago  8 10:28 modules-imx7s-warp.tgz -> modules--4.1-1.0.x+git0+b8fb01d418-r0-imx7s-warp-20160808132254.tgz
-rw-r--r-- 2 user user      294 Ago  8 12:55 README_-_DO_NOT_DELETE_FILES_IN_THIS_DIRECTORY.txt
lrwxrwxrwx 1 user user       47 Ago  8 10:31 u-boot.imx -> u-boot-sd-v2016.07+gitAUTOINC+ae973bc45d-r0.imx
lrwxrwxrwx 1 user user       47 Ago  8 10:31 u-boot-imx7s-warp.imx -> u-boot-sd-v2016.07+gitAUTOINC+ae973bc45d-r0.imx
lrwxrwxrwx 1 user user       47 Ago  8 10:31 u-boot-imx7s-warp.imx-sd -> u-boot-sd-v2016.07+gitAUTOINC+ae973bc45d-r0.imx
lrwxrwxrwx 1 user user       47 Ago  8 10:31 u-boot.imx-sd -> u-boot-sd-v2016.07+gitAUTOINC+ae973bc45d-r0.imx
-rwxr-xr-x 2 user user   347136 Ago  8 10:31 u-boot-sd-v2016.07+gitAUTOINC+ae973bc45d-r0.imx
lrwxrwxrwx 1 user user       66 Ago  8 10:28 zImage -> zImage--4.1-1.0.x+git0+b8fb01d418-r0-imx7s-warp-20160808132254.bin
-rw-r--r-- 2 user user  6514048 Ago  8 10:28 zImage--4.1-1.0.x+git0+b8fb01d418-r0-imx7s-warp-20160808132254.bin
-rw-r--r-- 2 user user    33845 Ago  8 10:28 zImage--4.1-1.0.x+git0+b8fb01d418-r0-imx7s-warp-20160808132254.dtb
lrwxrwxrwx 1 user user       66 Ago  8 10:28 zImage-imx7s-warp.bin -> zImage--4.1-1.0.x+git0+b8fb01d418-r0-imx7s-warp-20160808132254.bin
lrwxrwxrwx 1 user user       66 Ago  8 10:28 zImage-imx7s-warp.dtb -> zImage--4.1-1.0.x+git0+b8fb01d418-r0-imx7s-warp-20160808132254.dtb

The complete image (rootfs + kernel)  is **core-image-base-imx7s-warp-20160808155513.rootfs.sdcard.gz** (the numbers on image name vary depending on build date)

=== Steps to update the image

.board steps (u-boot)
[source,console]
=> ums 0 mmc 0

.host steps
[source,console]
$ gunzip core-image-base-imx7s-warp-20160808155513.rootfs.sdcard.gz
$ sudo dd if=core-image-base-imx7s-warp-20160808155513.rootfs.sdcard of=/dev/sdX

It may take few minutes. As soon as the dd command is finished, you can reboot the board.
