== The Android system for WaRP 7 board

=== Building the Android platform for WaRP7

The first step is to prepare the host machine and download the source
code.

==== Download the Android source code

The Android source code is maintained as more than 100 Git repositories
in the Android repository (http://android.googlesource.com/[_http://android.googlesource.com/_]).

To get the Android source code for WaRP7, follow the steps below:

All the steps are done in Linux Host (Ubuntu)
[source,console]
$ cd ~
$ mkdir myandroid
$ mkdir bin
$ cd myandroid
$ curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$ chmod a+x ~/bin/repo
$ ~/bin/repo init -u https://github.com/WaRP7/android_manifest.git -b imx_L5.1.1_2.0.0_7d-beta
$ ~/bin/repo sync
# this command loads most needed repos. Therefore, it can take severalhours to load.
$ cd ~/myandroid/prebuilts/gcc/linux-x86/arm
$ git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6
$ cd arm-eabi-4.6
$ git checkout android-4.4.3_r1

NOTE::
If you want to download the origin source code from AOSP, please see https://android.googlesource.com/[_https://android.googlesource.com/_]

==== Building Android images

Two commands are executed to build: one is lunch <buildName-buildType> to set up the build configuration, and the other is make to start the build process.

The build configuration command lunch can be issued with an argument Build Name – Build Type string, such as lunch warp7-eng, or can be issued without the argument presenting a menu of selection.

Android build steps are as follows:

1. Change to the top level build directory.
[source,console]
$ cd ~/myandroid

2. Set up the environment for building. This only configures the
current terminal.
[source,console]
$ source build/envsetup.sh

3. Execute the Android lunch command.
[source,console]
$ lunch warp7-eng

4. Execute the make command to generate the image.
[source,console]
$ make 2>&1 | tee build-log.txt

When the make command is complete, the build-log.txt file contains the execution output. Please check for any errors.

The following outputs are generated by default in myandroid/out/target/product/warp7:

- root/: root file system (including init, init.rc). Mounted at /

- system/: Android system binary/libraries. Mounted at /system.

- data/: Android data area. Mounted at /data.

- recovery/: root file system when booting in "recovery" mode. Not used directly.

- boot-imx7d.img: composite image for i.MX 7, which includes the kernel zImage, ramdisk, board's device tree binary, and boot parameters.

- ramdisk.img: ramdisk image generated from "root/". Not used directly.

- system.img: EXT4 image generated from "system/". It can be programmed to "SYSTEM" partition on SD/eMMC card with "dd".

==== Building kernel for Android

The kernel for Android has special drivers such as binder, lowmemkiller, etc, it also intergrated the Android root, use following steps to download and build kernel for Android:
[source,console]
$ git clone https://github.com/WaRP7/linux-fslc.git
$ cd linux-fslc
$ git checkout -b <name_your_branch> origin/linux_4.1.29

Use the commands below to compile:
[source,console]
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- mrproper
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-imx_v7_android_defconfig
$ cp ~/myandroid/out/target/product/warp7/root/ . -r
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- imx7d-warp.dtb

=== Updating The Android image

Power up your WaRP7, U-boot prompt will come (use any serial console i.e. minicom).

Run the following command on u-boot:
[source,console]
=> ums 0 mmc 0

You will be able to see emmc as storage device on your computer.

Use any standard utility to make partition table. (i.e. gparted).

Create 3 partitions, a 100MB FAT32 partition and a 500MB ext4 partition for system image, define the remaing space as an ext4 partition for user data.

Copy zImage to the fat32 partition.

Copy imx7s-warp.dtb to the fat32 partition.

Use dd utility to flash the system image to the second partition:
[source,console]
$ sudo dd if=~/myandroid/out/target/product/warp7/system.img of=/dev/sdX

Unmount the partitions using:
[source,console]
$ sudo umount /dev/sd<X>

In u-boot prompt, hit *Ctrl+C*, to cancel the mounted mmc. Then set the bootargs to boot Android:
[source,console]
=> setenv bootargs console=ttymxc0,115200 init=/initandroidboot.hardware=freescale androidboot.selinux=disabled;

Reboot your board, Android must be up and running.
